--UPDATE AND DELETE STATEMENTS
--STORE_ADMIN
UPDATE STORE_ADMIN SET Admin_name = 'Gabriel B. Gill' WHERE Admin_ID = 'ADM004';
DELETE FROM STORE_ADMIN WHERE Admin_ID = 'ADM006';


--CUSTOMER
UPDATE CUSTOMER SET Cust_phone_no = '5120972104' WHERE Cust_ID = 'CUST001';
DELETE FROM CUSTOMER WHERE Cust_ID = 'CUST004';


--AUTHOR
UPDATE AUTHOR SET Biography = 'Author of IT and Misery' WHERE Auth_ID = 'AUTH005';
DELETE FROM AUTHOR WHERE Auth_ID = 'AUTH008';


--BOOK
UPDATE BOOK SET Stk_Quant = 95 WHERE ISBN = 'ISBN002';
DELETE FROM BOOK WHERE Price < 8.00;


--REVIEW
UPDATE REVIEW SET Rating = 4 WHERE ReviewerID = 'CUST005' AND ReviewedID = 'ISBN005';
DELETE FROM REVIEW WHERE ReviewerID = 'CUST003' AND ReviewedID = 'ISBN007';


--WRITES
UPDATE WRITES SET Work_ID = 'ISBN006' WHERE Writer_ID = 'AUTH006';
DELETE FROM WRITES WHERE Work_ID = 'ISBN007' AND Writer_ID = 'AUTH007';


--CATEGORY_GENRE
UPDATE CATEGORY_GENRE SET Cat_Name = 'Modern Fantasy' WHERE Cat_ID = 'CAT006';
DELETE FROM CATEGORY_GENRE WHERE Cat_ID = 'CAT004';


--CATEGORIZATION
UPDATE CATEGORIZATION SET Cgz_catID = 'CAT001' WHERE Cgz_bookID = 'ISBN005';
DELETE FROM CATEGORIZATION WHERE Cgz_catID = 'CAT003' AND Cgz_bookID = 'ISBN003';


--STORE_ORDER
UPDATE STORE_ORDER SET Ship_Status = 'Delivered' WHERE Ord_ID = 'ORD005';
DELETE FROM STORE_ORDER WHERE Ord_ID = 'ORD007';
--PAYMENT_REC
UPDATE PAYMENT_REC SET Amount = 14.99 WHERE Pay_ID = 'PAY002';
DELETE FROM PAYMENT_REC WHERE Pay_ID = 'PAY006';


--PAYMENT_METHOD
UPDATE PAYMENT_METHOD SET Card_no = '7836023178924683' WHERE M_payID = 'PAY001' AND pay_Method = 'Credit Card';
DELETE FROM PAYMENT_METHOD WHERE M_payID = 'PAY005';


--ORDER_ITEM
UPDATE ORDER_ITEM SET Item_ID = 'ISBN001' WHERE Item_ordID = 'ORD002' AND Item_ID = 'ISBN002';
DELETE FROM ORDER_ITEM WHERE Item_ordID = 'ORD005' AND Item_ID = 'ISBN006';
